src/spacel/main.py
src/spacel/provision/alarm/endpoint/factory.py
src/spacel/provision/alarm/endpoint/pagerduty.py
src/spacel/provision/alarm/endpoint/slack.py
src/test/provision/alarm/endpoint/test_factory.py
src/test/provision/alarm/endpoint/test_pagerduty.py

If you built a service with CloudWatch integration, use `url`. This was
previously the only supported option.
If you built a service w/o CloudWatch integration, use `service`:
CloudWatch integration will be discovered, created if necessary.
If you built an escalation policy, use `escalation_policy`: an
appropriately named service with CloudWatch integration will be
discovered, created if necessary.
`escalation_policy` is targetting as the most sane default: having clean
Service names in PagerDuty make it easier to grok an incoming page at
2am.

PagerDuty improvements

---

sample/app/http-env-echo-alarms.json
src/spacel/provision/alarm/trigger/factory.py
src/spacel/provision/alarm/trigger/metrics.py
src/test/provision/alarm/trigger/test_factory.py

Instead of automatically scoping to the ASG/ELB, if you know the
`Namespace`, `MetricName`, `Dimensions` you can tie into anything you
fancy.
Update the alarm sample application to trigger scaling based on SQS
queue depth.
Refactor `dimensions` logic to be more user-friendly (since they can be
defined in parameters now).

WEBOPS-898: fully custom CW triggers

---

src/spacel/provision/alarm/endpoint/scale.py
src/test/provision/alarm/endpoint/test_scale.py

Since these are sourced from JSON, this is how they'll usually be input
(percentages especially).
Failing test case on Python2 threw:
`TypeError: bad operand type for abs(): 'unicode'`
Fixing said test case with small refactor: cast earlier.

Hotfix: explicit tests for string scaling sets

---

sample/app/http-env-echo-redis.json
src/spacel/main.py
src/spacel/model/orbit.py
src/spacel/provision/alarm/endpoint/pagerduty.py
src/spacel/provision/cache/factory.py
src/spacel/provision/changesets.py
src/spacel/provision/orbit/space.py
src/spacel/provision/template/__init__.py
src/spacel/provision/template/app.py
src/spacel/provision/template/ingress_resource.py
src/test/provision/cache/test_factory.py
src/test/provision/orbit/test_space.py
src/test/provision/template/test_app.py
src/test/provision/template/test_ingress_resource.py

Now a cache can expose itself to:
* another application in the same orbit
And less importantly (due to caches being VPC-private)
* an IP block
* all NAT-ed applications in another region of the same orbit
The latter are breadcrumbs for other internet-facing bits (i.e. `public_ports`, RDS).
Fixes #5

Cache ingress rules

---

sample/app/http-env-echo-spot.json
src/spacel/cloudformation/elb-service.template
src/spacel/cloudformation/vpc.template
src/spacel/main.py
src/spacel/model/app.py
src/spacel/model/orbit.py
src/spacel/provision/changesets.py
src/spacel/provision/orbit/space.py
src/spacel/provision/provision.py
src/spacel/provision/template/__init__.py
src/spacel/provision/template/app.py
src/spacel/provision/template/app_spot.py
src/test/provision/template/test_app.py
src/test/provision/template/test_app_spot.py

This is a template decorator that replaces the `Asg` resource with a
`SpotFleet` with the same parameters.
It _should_ work with internal templates too: there's some special code
for cleaning up GDH bits that reference the ASG. (untested).
FleetSpotting: choose 1 c4.xlarge, choose 2 c4.large, choose 4 m4.large, choose life.
https://www.youtube.com/watch?v=RCxgqHqakXc

WEBOPS-963: SpotFleet support

---

sample/app/http-env-echo.json
src/spacel/main.py
src/spacel/model/__init__.py
src/spacel/model/app.py
src/spacel/provision/template/app.py
src/spacel/security/__init__.py
src/test/__init__.py
src/test/model/test_app.py
src/test/provision/template/test_app.py

When the public_port is declared as SSL/HTTPS, use ACM as a fallback if
no specific certificate is given.
Improved handling around port number->scheme mapping: you shouldn't need
to declare that 443 is HTTPS.

Finish ACM integration

---

sample/orbit/develop.json
src/spacel/cloudformation/elb-service.template
src/spacel/provision/template/app.py
src/spacel/provision/template/app_spot.py
src/test/provision/template/test_app_spot.py

Added support for tags in [spacel-agent](https://github.com/pebble/spacel-agent/pull/21), because spot fleet does not support setting tags.
Deliberated on adding a unique identifier (we use GitDeployIdentifier tag), but followed `spacel-provision` rules (https://github.com/pebble/spacel-provision/blob/master/src/spacel/cloudformation/elb-service.template#L540)
~~Alternatively, this code can/should be moved to `Ref: UserData` to only be included when we use spot?~~ rewritten to go via the `UserData` param so we only feed it when we need to.

Spot instances need to set their own tags

---

src/spacel/provision/template/app_spot.py

* Duplicated `SpScaleDown`, meant to change to `SpScaleUp`
* Missed `AlarmHighContinuousLoad` altogether

WEBOPS-963: update SpotFleet GDH cleanup

---

src/spacel/provision/alarm/trigger/factory.py
src/test/provision/alarm/trigger/test_factory.py

That was pretty silly.
Special test case to ensure the added `.` isn't a RegExp wildcard.

TriggerFactory: support decimals

---

src/spacel/provision/alarm/endpoint/pagerduty.py
src/test/provision/alarm/endpoint/test_pagerduty.py

1) let 'url' be processed before any parameters (to avoid extracting
fields we don't need)
2) Support `asg-application`, which uses slightly different parameter
names.

PagerDuty: support GDH templates

---

src/spacel/provision/template/app_spot.py

Upstream git-deploy-hooks does not have a `UserData` parameter, so this breaks on:
```
remote:   File "/tmp/git-deploy-virtualenv-webops/local/lib/python2.7/site-packages/spacel/provision/template/app_spot.py", line 36, in _add_spot_fleet
remote:     user_data_param = parameters['UserData']['Default'] or ''
remote: KeyError: 'UserData'
```
This check prevents that.

Skip trying to set parameters if UserData param does not exist

---

src/spacel/aws/ami.py
src/spacel/model/app.py
src/spacel/provision/db/cache.py
src/spacel/provision/template/app.py
src/test_integ/__init__.py
src/test_integ/test_deploy.py

This uses https://github.com/pebble/spacel-agent/pull/25 to integrate
`REDIS_URL` with the hosted laika.
Upgrade Redis version:
https://aws.amazon.com/about-aws/whats-new/2016/10/amazon-elasticache-for-redis-adds-sharding-support-with-redis-cluster/

Redis integration test

---

src/spacel/provision/changesets.py
src/spacel/provision/cloudformation.py
src/spacel/provision/db/rds.py
src/test/provision/db/test_rds.py
src/test_integ/__init__.py
src/test_integ/test_deploy.py

Grant `DescribeDbInstances` for managed RDS instances.
✋ Won't break anything, but useless+untested as is.

RDS integration WIP

---

Dockerfile

When attempting to roll out a new app using `pebbletech/spacel-provision` docker, the following output would be returned as soon as it came to fetching the AMI:
```
[REDACTED]
2016-10-30 15:42:14,575 - DEBUG - spacel.aws.ami - AMI manifest https://ami.pbl.io/spacel/stable.json not cached, fetching...
Traceback (most recent call last):
File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
h.request(req.get_method(), req.selector, req.data, headers)
[REDACTED]
File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
[REDACTED]
File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: …
```

Allow AMI to be fetched from remote URL

---

src/spacel/cloudformation/asg-bastion.template
src/spacel/provision/cloudformation.py
src/spacel/provision/template/app.py
src/spacel/provision/template/bastion.py
src/test/provision/template/test_bastion.py

All VPCs get:
* `${region}.${orbit}.${domain}`
* `us-east-1.sl-test.pebbledev.com`
If there's >1 bastion host, aliases are created for each:
* `bastionNN.${region}.${orbit}.${domain}`
* `bastion02.us-east-1.sl-test.pebbledev.com`
Note: in the multi-bastion case, the `01` node has two names.
Round-robin would have been cool, but SSH thinks it looks like DNS
spoofing.
Fixes #35

Bastion DNS aliases

---

sample/app/laika-systemd.json
sample/orbit/sl-test.json
src/spacel/model/app.py
src/spacel/provision/changesets.py
src/spacel/provision/template/app.py
src/test/model/test_app.py
src/test/provision/template/test_app.py
src/test_integ/__init__.py
src/test_integ/test_deploy.py
src/test_integ/test_persistence.py

Our artisinal systemd units are handcrafted to order.
Migrating where `foo` -> `foo.service` correction takes place for
consistency with generated docker units.
Splitting persistence integration tests out from regular old deployment.
Fixes #37

Provide fulltext unit systemd sample/test

---

src/spacel/cloudformation/elb-service.template
src/spacel/main.py
src/spacel/model/app.py
src/spacel/provision/cloudformation.py
src/spacel/provision/provision.py
src/test/provision/test_cloudformation.py
src/test_integ/__init__.py
src/test_integ/test_deploy.py
src/test_integ/test_failure.py

* Refactor wait_for_updates to detect any CF stacks that rollback
* Suspend `ReplaceUnhealthy` during `UpdatePolicy`; otherwise the
defaults have the ASG recycling instances (600s) while instances are
waiting to be healthy in the Elb (900s).
* Refactor templated units to `Wants=spacel-agent` instead of
`Requires=`; this prevents downstream units automatically restarting
when spacel-agent is restarted (noticed spacel-agent never sees running
units while testing https://github.com/pebble/spacel-agent/pull/38 )

Integration test failures

---

README.md
docker-compose.yml
src/spacel/aws/ami.py
src/spacel/main.py
src/test_integ/__init__.py
src/test_integ/test_deploy.py

- Accept `SPACEL_AGENT_CHANNEL` environment parameter for toggling
between `latest` and `stable` AMIs. (avoiding `AMI` in this variable, as the ability to pull a `docker container/tag` may be handy while working on `spacel-agent` changes? (AMI packaging is slow!)
- Now src/test_integ/* can be executed with a `latest` AMI to verify it
before promoting to `stable`; neato!
- Prefer `0.1.1` for tests instead of `0.1.0`; version injection botched
the `0.1.0` build on DockerHub so it doesn't return the expected
version!

WEBOPS-945: integration test per-entry decryption

---

sample/app/http-env-echo-no-loadbalancer.json
sample/orbit/develop.json
src/spacel/cloudformation/elb-service.template
src/spacel/main.py
src/spacel/model/app.py
src/spacel/provision/template/app.py
src/spacel/security/kms_key.py
src/test/model/test_app.py
src/test/provision/template/test_app.py

- Set `"loadbalancer": "false"` to skip creating a loadbalancer
- Set `"availability": "public"` to create instances in a public subnet, and to give them a public IP address (prelude to #45, #50 comes to mind)
tested on develop ✅ 
Fixes #47

Make ELB not required

---

src/spacel/aws/ami.py
src/spacel/main.py
src/test/aws/test_ami.py
src/test_integ/__init__.py
src/test_integ/test_persistence.py

Teach AmiFinder how to skip local+CloudFront cache: implementing this is
faster than waiting for the AMI with https://github.com/pebble/spacel-agent/pull/28 to land :P

WEBOPS-565: Verify RDS integration

---

sample/orbit/develop.json
src/spacel/model/orbit.py
src/spacel/provision/app/space.py
src/spacel/provision/template/app.py
src/spacel/provision/template/vpc.py
src/test/provision/app/test_space.py
src/test/provision/template/test_app.py
src/test/provision/template/test_vpc.py

Fixes #45 
This makes it possible to deploy a $5/m (`t2.nano`) in just a few minutes with `spacel-provision`.
When trying to use `private` with NAT gateway disabled, we return an error and skip trying to deploy that template. Private subnets are pointed via the internet gateway to keep them around.

Feature flag: disable NAT gateway

---

sample/app/http-env-echo-bare-minimum.json
sample/app/http-env-echo-elastic-ips.json
sample/orbit/develop.json
src/spacel/model/app.py
src/spacel/provision/app/ingress_resource.py
src/spacel/provision/template/app.py
src/test/provision/app/test_ingress_resource.py
src/test/provision/template/test_app.py
src/test_integ/__init__.py
src/test_integ/test_deploy.py

Adds feature flag to apps: `elastic_ips: "enabled||disabled"`
Fixes #50
This is still missing:

Feature flag: Elastic IPs for Apps

---

src/spacel/model/app.py
src/spacel/provision/template/app.py
src/test/provision/template/test_app.py
src/test_integ/test_deploy.py

This tells `spacel-agent` that we want `cloudwatch-stats.service`
started, pretty please.
Requires:
- https://github.com/pebble/vz-spacel-agent/pull/8
- https://github.com/pebble/spacel-agent/pull/42

WEBOPS-972: `AppRegion.stats` flag

---

src/spacel/cli/provision.py
src/spacel/provision/app/__init__.py
src/spacel/provision/app/db/base.py
src/spacel/provision/app/ingress_resource.py
src/spacel/provision/template/app.py
src/test/provision/app/test_ingress_resource.py
src/test/provision/template/test_app.py

This is 50% planned refactor: backport `IngressResourceFactory`(introduced for ElastiCache/RDS support) to the `SpaceApp.public_ports[].sources[]` structure.
This provides stronger security for `elb_availability=private` applications (i.e. a `kafka` app could whiltelist specific producers/consumers, instead of allowing the entire VPC by CIDR). Noice.
The other 50% is propagating the `availability` flag to IngressResourceFactory, so that it can make the user think twice before exposing a `elb_availability=multi-region` service as if it were `elb_availability=public`. 
The latter fixes #56

Apps use ingress resource factory

---

src/spacel/cli/helper.py
src/spacel/cli/provision.py
src/spacel/model/service.py
src/test/cli/test_helper.py
src/test/cli/test_provision.py
src/test/model/test_service.py

This is for Jenkins: it wants to deploy with `.space/app.json` from the
target repository, _but_ bumping that file with every release is really annoying.
This should behave nicely with: https://github.com/pebble/spacel-laika/blob/master/.space/app.json#L10

App version/docker tag via CLI

---

spacel.sh
src/spacel/cli/helper.py
src/spacel/cli/provision.py
src/spacel/cli/secret.py
src/spacel/main.py
src/test/test_main.py

Tiny bit of bash makes running `spacel-provision` from docker a little
friendlier.
Removed legacy_args handling as it messed with bash completion:
call it <1.0 freedom.
Removed said bash completion WIP because it was god-awful slow.

spacel wrapping script

---

src/spacel/cli/provision.py
src/spacel/cloudformation/elb-service.template
src/spacel/provision/app/space.py
src/spacel/provision/cloudformation.py
src/test/cli/test_provision.py
src/test/provision/app/test_space.py
src/test/provision/test_cloudformation.py

Sometimes you just don't trust the instances you're running on, and want
new ones. Make that possible without requiring manifest-level NOOPs.
Fixes #66

`spacel provision --force`
